plugins {
	id 'java-library'
	id 'application'
}

repositories {
	mavenCentral()
}

dependencies {
	testImplementation platform("org.junit:junit-bom:${project.junit_version}")
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testImplementation "com.google.code.gson:gson:${project.gson_version}"
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.release = 21
	options.encoding = 'UTF-8'
}

application {
	mainClass = 'dev.mcskylines.bridge.conformance.Main'
	applicationName = 'bridge'
}

test {
	useJUnitPlatform()
	systemProperty 'mcskylines.vectors', rootProject.file('../protocol/vectors').absolutePath
}
